
namespace ThreadsAppp
{
    partial class Form2
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.StopButton = new System.Windows.Forms.Button();
            this.listView = new System.Windows.Forms.ListView();
            this.threadId = new System.Windows.Forms.ColumnHeader();
            this.data = new System.Windows.Forms.ColumnHeader();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(75, 54);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(482, 25);
            this.label1.TabIndex = 0;
            this.label1.Text = "Here are the last 20 data entries, generated by the Threads: ";
            this.label1.Click += new System.EventHandler(this.label1_Click);
            // 
            // StopButton
            // 
            this.StopButton.Location = new System.Drawing.Point(619, 371);
            this.StopButton.Name = "StopButton";
            this.StopButton.Size = new System.Drawing.Size(155, 54);
            this.StopButton.TabIndex = 1;
            this.StopButton.Text = "Stop";
            this.StopButton.UseVisualStyleBackColor = true;
            this.StopButton.Click += new System.EventHandler(this.StopButton_Click);
            // 
            // listView
            // 
            this.listView.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.threadId,
            this.data});
            this.listView.HideSelection = false;
            this.listView.Location = new System.Drawing.Point(30, 89);
            this.listView.Name = "listView";
            this.listView.Size = new System.Drawing.Size(743, 282);
            this.listView.TabIndex = 2;
            this.listView.UseCompatibleStateImageBehavior = false;
            // 
            // threadId
            // 
            this.threadId.Text = "Thread ID";
            // 
            // data
            // 
            this.data.Text = "Data";
            this.data.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.data.Width = 80;
            // 
            // Form2
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 25F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.listView);
            this.Controls.Add(this.StopButton);
            this.Controls.Add(this.label1);
            this.Name = "Form2";
            this.Text = "Form2";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button StopButton;
        private System.Windows.Forms.ListView listView;
        private System.Windows.Forms.ColumnHeader threadId;
        private System.Windows.Forms.ColumnHeader data;
    }
}